### ISSUE TITLE
Make rails use Puma to allow for SSEs

### ISSUE THREAD

**Issue by Kalior** [cthit/HueIT-Rails#24]
So that #21 and #22 can be achieved

**Comment by lindskogen** [comment]
Server-sent events? Cool!

**Comment by Kalior** [comment]
This will not be necessary since passenger supports sse. Might still be needed for development though.

**Comment by Kalior** [comment]
Apparently SSEs won't work in passanger with apache integration mode. So maybe Puma after all?

**Comment by Portals** [comment]
Closing because of rewrite
