### ISSUE TITLE
UI messed up in Firefox

### ISSUE THREAD

**Issue by SSundstrom** [cthit/HueIT-Rails#27]

**Comment by lindskogen** [comment]
Please describe issue in more detail. Or attach a screenshot!

**Comment by Kalior** [comment]
It's related to getcsscanvascontext which is not supported in firefox, ie, edge, opera

**Comment by lindskogen** [comment]
So, it's the graphs?

**Comment by Kalior** [comment]
It's the party button, the sliders and the "bulb"
